name: repos
description: "app_qi"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  calendar_agenda: ^0.0.2+3
  horizontal_week_calendar: ^0.0.7
  carousel_slider: ^4.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

   # To add assets to your application, add an assets section, like this:
  assets:
     - assets/imagens/logoentrar.png
     - assets/imagens/imagen.inicio.png
     - assets/imagens/cruz.png