name: repos
description: "app_qi"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  calendar_agenda: ^0.0.2+3
  horizontal_week_calendar: ^0.0.7
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  horizontal_calendar: ^1.1.1
  table_calendar: ^3.0.8
  web_socket_channel: ^2.4.5
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  responsive_styles: ^2.3.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  provider: ^6.1.2
  firebase_database: ^10.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.6.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9


flutter:

  
  uses-material-design: true

   # To add assets to your application, add an assets section, like this:
  assets:
     - assets/imagens/logoentrar.png
     - assets/imagens/imagen.inicio.png
     - assets/imagens/cruz.png
     - assets/imagens/telaconsulta.jpg
     - assets/imagens/hospitalj.jpeg