// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBweKEIk4BZ38tE0XVP74z1iZxt55wTxyc',
    appId: '1:381454349421:web:5636d2cda5834b08efbb64',
    messagingSenderId: '381454349421',
    projectId: 'projeto-qi-32dbd',
    authDomain: 'projeto-qi-32dbd.firebaseapp.com',
    databaseURL: 'https://projeto-qi-32dbd-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-qi-32dbd.appspot.com',
    measurementId: 'G-RT42FW33K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDX30SCOqOmPmJAFndVP-PVez0uueb_XQ',
    appId: '1:381454349421:android:b24d349ce3a38736efbb64',
    messagingSenderId: '381454349421',
    projectId: 'projeto-qi-32dbd',
    databaseURL: 'https://projeto-qi-32dbd-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-qi-32dbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1FZDatgG7bMtu-UU5_Vc4tmucwomMEnQ',
    appId: '1:381454349421:ios:8713d6117d26fcfcefbb64',
    messagingSenderId: '381454349421',
    projectId: 'projeto-qi-32dbd',
    databaseURL: 'https://projeto-qi-32dbd-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-qi-32dbd.appspot.com',
    iosBundleId: 'com.example.repos',
  );
}
